[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则-在线更新版 https://github.com/ACL4SSR/ACL4SSR/blob/master/Clash/config/ACL4SSR_Online.ini

ruleset=🤖 GenAI ꚰ🇸🇬ꚰ,https://raw.githubusercontent.com/synalocey/SusyModifier/master/list/AI-Platform.list
ruleset=🪜 General,https://raw.githubusercontent.com/synalocey/SusyModifier/master/list/ProxySK.list
ruleset=🪜 General,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🪜 General,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🪜 General,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🪜 General,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list

ruleset=💻 MDPI ꚰDꚰ,https://raw.githubusercontent.com/synalocey/SusyModifier/master/list/Email-IMAP.list
ruleset=DIRECT,https://raw.githubusercontent.com/synalocey/SusyModifier/master/list/LocalAreaNetwork.list
ruleset=🎓 WoS ꚰDꚰ,https://raw.githubusercontent.com/synalocey/SusyModifier/master/list/WoS.list
ruleset=💻 MDPI ꚰDꚰ,https://raw.githubusercontent.com/synalocey/SusyModifier/master/list/MDPI.list

ruleset=DIRECT,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=DIRECT,https://raw.githubusercontent.com/synalocey/SusyModifier/master/list/ChinaDomain.list
ruleset=DIRECT,[]GEOIP,CN
ruleset=🐟 漏网之鱼 ꚰ🪜ꚰ,[]FINAL

custom_proxy_group=🪜 General`select`[]⚡️ Auto-HK`[]⚡️ Auto-SG`.*
custom_proxy_group=🎓 WoS ꚰDꚰ`select`[]DIRECT`[]🪜 General
custom_proxy_group=💻 MDPI ꚰDꚰ`select`[]DIRECT`[]🪜 General`.*`https://susy.mdpi.com/build/img/icon/pencil.png`300,,40
custom_proxy_group=🤖 GenAI ꚰ🇸🇬ꚰ`select`[]⚡️ Auto-SG`^(?!.*(香港|Hong Kong|HK))`[]🪜 General
custom_proxy_group=🐟 漏网之鱼 ꚰ🪜ꚰ`select`[]🪜 General`[]DIRECT
custom_proxy_group=⚡️ Auto-HK`url-test`(香港|Hong Kong|HK|官方优选)
custom_proxy_group=⚡️ Auto-SG`url-test`(新加坡|Singapore)

enable_rule_generator=true
overwrite_original_rules=true

clash_rule_base=https://raw.githubusercontent.com/synalocey/SusyModifier/master/GeneralClashConfig.yml
