mixed-port: 7890
allow-lan: true

# 仅在将allow-lan设置为true时适用
# #"*": 绑定所有IP地址
# #192.168.122.11: 绑定单个IPv4地址
# #"[aaaa::a8aa:ff:fe09:57d8]": 绑定单个IPv6地址
bind-address: "*"
ipv6: true
mode: rule

# 5 个级别：silent / error / warning / info / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info

# Clash 的 RESTful API
external-controller: :9090
unified-delay: true

sniffer:
  sniff:
    TLS: {ports: [443], override-destination: true}
    HTTP: {ports: [443], override-destination: true}
  enable: true
  skip-domain:
    - Mijia Cloud
    - dlg.io.mi.com
  parse-pure-ip: false
  force-dns-mapping: true
  override-destination: true

# 实验性功能 hosts, 支持通配符 (例如 *.clash.dev 甚至 *.foo.*.example.com)
# 静态的域名 比 通配域名 具有更高的优先级 (foo.example.com 优先于 *.example.com)
# 注意: hosts 在 fake-ip 模式下不生效
hosts:
    "mail.mdpi.com": 195.65.194.210
    "*.mdpi.lab": 210.51.191.4
    "*.*.mdpi.lab": 210.51.191.4
    "merrin5.mdpi.lab": 210.51.191.7
    "feedback.mdpi.cn": 210.51.191.4
    "*.mdpi.test": 195.65.177.76
    "*.mdpi.intra": 195.65.177.76
    "*.mdpi.dev": 195.65.177.78
    "*.*.mdpi.test": 195.65.177.76
    "*.*.mdpi.intra": 195.65.177.76
    "*.*.mdpi.dev": 195.65.177.78

dns:
  enable: true # 是否启用dns false
  ipv6: false
  listen: 0.0.0.0:53
  use-hosts: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16 #
  fake-ip-filter:
    - "*.lan"
    - "stun.*.*.*"
    - "stun.*.*"
    - time.windows.com
    - time.nist.gov
    - "*.apple.com"
    - time.asia.apple.com
    - "*.ntp.org.cn"
    - "*.openwrt.pool.ntp.org"
    - time1.cloud.tencent.com
    - time.ustc.edu.cn
    - pool.ntp.org
    - ntp.ubuntu.com
    - "*.aliyun.com"
    - "*.time.edu.cn"
    - "time*.google.com"
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - "*.taihe.com"
    - "*.kugou.com"
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - "*.tc.qq.com"
    - "*.music.tc.qq.com"
    - "*.*.qqmusic.qq.com"
    - "*.xiami.com"
    - music.migu.cn
    - "*.music.migu.cn"
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - "*.ptlogin2.qq.com"
    - "*.*.*.srv.nintendo.net"
    - "*.*.stun.playstation.net"
    - "xbox.*.*.microsoft.com"
    - "*.ipv6.microsoft.com"
    - "*.*.xboxlive.com"
    - "*.bambulab.com"
    - "*.bambulab.cn"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - "time.*.com"
    - "time.*.gov"
    - "time.*.edu.cn"
    - "time.*.apple.com"
    - "time1.*.com"
    - "time2.*.com"
    - "time3.*.com"
    - "time4.*.com"
    - "time5.*.com"
    - "time6.*.com"
    - "time7.*.com"
    - "ntp.*.com"
    - "ntp1.*.com"
    - "ntp2.*.com"
    - "ntp3.*.com"
    - "ntp4.*.com"
    - "ntp5.*.com"
    - "ntp6.*.com"
    - "ntp7.*.com"
    - "+.pool.ntp.org"
    - swscan.apple.com
    - mesu.apple.com
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - localhost.ptlogin2.qq.com
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    - "teredo.*.*.*"
    - "teredo.*.*"
    - speedtest.cros.wr.pvp.net
    - "+.jjvip8.com"
    - www.douyu.com
    - activityapi.huya.com
    - activityapi.huya.com.w.cdngslb.com
    - www.bilibili.com
    - api.bilibili.com
    - a.w.bilicdn1.com
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 8.8.4.4
    - 1.0.0.1
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query
