#---------------------------------------------------#
# 配置文件需要放置在 $HOME/.config/clash/config.yml
# 或者运行目录下的config.yml
#---------------------------------------------------#
# 混合端口 HTTP和SOCKS5用一个端口
mixed-port: 7890

# HTTP 代理端口
# port: 7890

# SOCKS5 代理端口
# socks-port: 7891

# Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
# redir-port: 7892

# 允许局域网的连接（可用来共享代理）
allow-lan: true

# 仅在将allow-lan设置为true时适用
# #"*": 绑定所有IP地址
# #192.168.122.11: 绑定单个IPv4地址
# #"[aaaa::a8aa:ff:fe09:57d8]": 绑定单个IPv6地址
bind-address: "*"
ipv6: true

# 规则模式：rule（规则） / global（全局代理）/ direct（全局直连）/ script (脚本)
mode: rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / error / warning / info / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info

# Clash 的 RESTful API
external-controller: '127.0.0.1:9090'

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# http://127.0.0.1:9090/ui/#/
# external-ui: folder
# yacd面板：  https://github.com/haishanh/yacd
# Razord面板：http://clash.razord.top/#/proxies
# external-ui: dashboard

# RESTful API 的口令 (可选)
# secret: ""

# 实验性功能
experimental:
  ignore-resolve-fail: true # 忽略 DNS 解析失败，默认值为 true
  # interface-name: en0 # outbound interface name

# 本地 SOCKS5 / HTTP(S) 服务认证
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# 实验性功能 hosts, 支持通配符 (例如 *.clash.dev 甚至 *.foo.*.example.com)
# 静态的域名 比 通配域名 具有更高的优先级 (foo.example.com 优先于 *.example.com)
# 注意: hosts 在 fake-ip 模式下不生效
hosts:
    "mail.mdpi.com": 212.243.204.123
    "*.mdpi.lab": 210.51.191.4
    "*.*.mdpi.lab": 210.51.191.4
    "merrin5.mdpi.lab": 210.51.191.7
    "feedback.mdpi.cn": 210.51.191.4
    "*.mdpi.test": 195.65.177.76
    "*.mdpi.intra": 195.65.177.76
    "*.mdpi.dev": 195.65.177.78
    "*.*.mdpi.test": 195.65.177.76
    "*.*.mdpi.intra": 195.65.177.76
    "*.*.mdpi.dev": 195.65.177.78
    "api.dalaie.com": 140.238.9.12
tun:
  enable: false
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53
  macOS-auto-route: true
  macOS-auto-detect-interface: true 

dns:
  enable: true # 是否启用dns false
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16 #
  fake-ip-filter:
    - "*.lan"
    - "stun.*.*.*"
    - "stun.*.*"
    - "time.windows.com"
    - "time.nist.gov"
    - "*.apple.com"
    - "time.asia.apple.com"
    - "*.ntp.org.cn"
    - "*.openwrt.pool.ntp.org"
    - "time1.cloud.tencent.com"
    - "time.ustc.edu.cn"
    - "pool.ntp.org"
    - "ntp.ubuntu.com"
    - "*.aliyun.com"
    - "*.time.edu.cn"
    - "time*.google.com"
    - "music.163.com"
    - "*.music.163.com"
    - "*.126.net"
    - "*.taihe.com"
    - "*.kugou.com"
    - "*.kuwo.cn"
    - "api-jooxtt.sanook.com"
    - "api.joox.com"
    - "joox.com"
    - "y.qq.com"
    - "*.y.qq.com"
    - "*.tc.qq.com"
    - "*.music.tc.qq.com"
    - "*.*.qqmusic.qq.com"
    - "*.xiami.com"
    - "music.migu.cn"
    - "*.music.migu.cn"
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - "*.ptlogin2.qq.com"
    - "*.*.*.srv.nintendo.net"
    - "*.*.stun.playstation.net"
    - "xbox.*.*.microsoft.com"
    - "*.ipv6.microsoft.com"
    - "*.*.xboxlive.com"
  nameserver:
    - 114.114.114.114
    - 180.76.76.76
    - 223.5.5.5
  fallback: []

# 代理组
# 下面这3个不要引到订阅里去 要不会出错
# Will be ignored after profile selection
#proxies:
#  - name: Shadowsocks
#    type: socks5
#    server: 127.0.0.1
#    port: 1080
#proxy-groups:
#  - name: Proxy
#    type: select
#    proxies:
#      - Shadowsocks
#rules:
#  - 'MATCH,DIRECT'

# Clash for Windows
# Proxies module latency test settings
cfw-latency-timeout: 3000
cfw-latency-url: http://maps.google.com/generate_204

# 混合配置（mixin）
# 支持向所有配置文件中注入公共属性设置
#cfw-profile-mixin:
  #dns:
    #enable: true
    #listen: :53
    #enhanced-mode: fake-ip
    #nameserver:
     #- 223.5.5.5 # 阿里DNS
     #- 180.76.76.76 # 百度DNS
     #- 119.29.29.29 # 腾讯DNS
     #- 117.50.11.11 # ONE DNS拦截版 恶意网站拦截、广告过滤
     #- 117.50.10.10 # ONE DNS纯净版 直接返回其真实的响应结果
     #- 114.114.114.114 # 114DNS
  #experimental:
    #interface-name: WLAN

#自定义配置目录
#cfw-profiles-path: 'C:\Users\Administrator\.config\clash\profiles'

# 打断连接
# Identify strategy of breaking connections after switching to a new proxy/profile/mode
# Options for proxy: none, chain(proxy group in connection chains), all
# Options for profile: true, false
# Options for mode: true, false
cfw-conn-break-strategy:
  proxy: none # none/chain/all
  profile: true # true/false
  mode: false # true/false

# 自定义状态栏图标
#cfw-tray-icon:
#default: .\resources\static\imgs\logo_64.png        # 默认图标
#system-proxy-on: .\resources\static\imgs\custom.ico   # 开启系统代理后图标

# 自定义字体
#cfw-font-family: "Noto Sans TC"   # 系统中存在的字体

# 自定义请求头
#cfw-http-headers:
  #token: "123456"
  #cfw-version: "0.9.11"

# 自定义节点排序
# 可选参数：
#  default：按配置文件定义节点顺序
#  latency：按节点延迟升序排列
#  alphabet：按节点名称字母表排列
# Sort proxies in Proxies module by default/latency/alphabet
# cfw-proxies-order: default

# 子进程 启动其他应用
# Run child process after CFW started
# Refer: https://docs.cfw.lbyczf.com/contents/childprocess.html
#cfw-child-process:
  # 启动订阅转换程序，端口号7893
  #- command: "subconverter.exe" # run.cmd 程序名称 subconverter.exe -cfw >>logs/run.log 2>&1
    #args:
      #- "-cfw" # 运行参数1
      #- "-f" # 运行参数2
      #- "pref-acl4ssr.yml" # 运行参数3
    #options:
      #cwd: subconverter # 子进程工作目录
      #detached: true # 子进程独立于其父进程运行
      #shell: true # 则在 shell 中运行 command
      #windowsHide: true # 隐藏子进程的控制台窗口
  # 启动网易云，端口号3333
  #- command: "unblockneteasemusic.exe" # 启动网易云
    #args:
      #- "-p" # 运行参数1
      #- "3333" # 运行参数2
    #options:
      #cwd: unblockNeteaseMusic # 子进程工作目录
      #detached: true # 子进程独立于其父进程运行
      #shell: true # 则在 shell 中运行 command
      #windowsHide: true # 隐藏子进程的控制台窗口

# 系统代理跳过列表 cfw-bypass
# System proxy will ignore these domains(or ipnet)
cfw-bypass:
  # 原有字段不用删除
  - localhost
  - 127.*
  - 10.*
  - 172.16.*
  - 172.17.*
  - 172.18.*
  - 172.19.*
  - 172.20.*
  - 172.21.*
  - 172.22.*
  - 172.23.*
  - 172.24.*
  - 172.25.*
  - 172.26.*
  - 172.27.*
  - 172.28.*
  - 172.29.*
  - 172.30.*
  - 172.31.*
  - 192.168.*
  - 188.188.1.*
  - 224.*
  - 225.*
  - 226.*
  - 227.*
  - 228.*
  - 229.*
  - 230.*
  - 231.*
  - 232.*
  - 233.*
  - 234.*
  - 235.*
  - 236.*
  - 237.*
  - 238.*
  - 239.*
  - 255.*
  - <local>
  - "*.msftconnecttest.com"
  - "*.msftncsi.com"
  
